services:
  mongo:
    image: mongo:latest
    container_name: zinc-mongo
    restart: always
    hostname: zinc-mongo
    command: --oplogSize 128 --bind_ip_all --port 60001
    volumes:
      - zinc-mongo_data:/data/db
      - zinc-mongo_configdb:/data/configdb
    ports:
      - "60001:60001"

volumes:
  zinc-mongo_data:
  zinc-mongo_configdb: